version: "3.7"
services:

  mysqldb:
    image: "mysql:5.7.15"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: roomless
networks:
  springapimysql-net: